baseURL = "https://hai.cherrynotperfect.me/"
languageCode = 'en-us'
title = "à¼— âŠğ’ğ’½ğ‘’ğ“‡ğ“‡y ğ’©ğ‘œğ“‰ ğ’«ğ‘’ğ“‡ğ’»ğ‘’ğ’¸ğ“‰"
paginate = 5

pygmentsstyle = "monokai"
pygmentscodefences = true

[params]
favicon = "/cherry.ico"
featherIconsCDN = true
subtitle = """
Hi I'm Cherry, and I a passionate learner, Feel free to look around. I dump a lot of text here, enjoy your stay and use the content at your own risk! 

<div style="text-align: right;">
  <img src="/cherry.gif" style="max-width: 100%; height: auto; border-radius: 20px;" alt="cherry.gif">
</div>
"""
   
[[params.social]]
name = "â¤œ ğ’¢ğ’¾ğ“‰ğ’½ğ“Šğ’· â¤›"
icon = "github"
url = "https://github.com/CherryNotPerfect"

[[params.social]]
name = "â¤œ â„ğ“ƒğ“ˆğ“‰ğ’¶ğ‘”ğ“‡ğ’¶ğ“‚ â¤›"
icon = "instagram"
url = "https://www.instagram.com/vercerher"

[[menu.main]]
name = "â®‘ğ“Œğ’½ğ‘œğ’¶ğ“‚ğ’¾"
url = "/whoami"
weight = 1

[[menu.main]]
name = "â®‘ğ“…ğ‘œğ“ˆğ“‰ğ“ˆ"
url = "/posts"
weight = 2

[[menu.main]]
name = "â®‘ğ‘”ğ’¶ğ“ğ“ğ‘’ğ“‡ğ“"
url = "/gallery"
weight = 3

[[menu.main]]
name = "â®‘ğ“‚ğ“ğ“ğ’¶ğ“ƒğ‘”ğ“Šğ’¶ğ‘”ğ‘’"
url = "/mylanguage"
weight = 4

[assets]
sources = ["assets"]

[markup.goldmark.renderer]
unsafe= true
